# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/danie/OneDrive/MSI_P65_Creator_8RE/Documentos/4_Carrera/TFG/Vivado2/HTDI20/HTDI20.srcs/sources_1/ip/dist_mem_gen_1/dist_mem_gen_1.xci
# IP: The module: 'dist_mem_gen_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/danie/OneDrive/MSI_P65_Creator_8RE/Documentos/4_Carrera/TFG/Vivado2/HTDI20/HTDI20.gen/sources_1/ip/dist_mem_gen_1/dist_mem_gen_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_mem_gen_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/danie/OneDrive/MSI_P65_Creator_8RE/Documentos/4_Carrera/TFG/Vivado2/HTDI20/HTDI20.srcs/sources_1/ip/dist_mem_gen_1/dist_mem_gen_1.xci
# IP: The module: 'dist_mem_gen_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/danie/OneDrive/MSI_P65_Creator_8RE/Documentos/4_Carrera/TFG/Vivado2/HTDI20/HTDI20.gen/sources_1/ip/dist_mem_gen_1/dist_mem_gen_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_mem_gen_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
