# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/danie/OneDrive/MSI_P65_Creator_8RE/Documentos/5_Carrera/TFG/Github/HTDI20/HTDI20_v3.srcs/sources_1/ip/UCROM/UCROM.xci
# IP: The module: 'UCROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/danie/OneDrive/MSI_P65_Creator_8RE/Documentos/5_Carrera/TFG/Github/HTDI20/HTDI20_v3.srcs/sources_1/ip/UCROM/UCROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'UCROM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/danie/OneDrive/MSI_P65_Creator_8RE/Documentos/5_Carrera/TFG/Github/HTDI20/HTDI20_v3.srcs/sources_1/ip/UCROM/UCROM.xci
# IP: The module: 'UCROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/danie/OneDrive/MSI_P65_Creator_8RE/Documentos/5_Carrera/TFG/Github/HTDI20/HTDI20_v3.srcs/sources_1/ip/UCROM/UCROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'UCROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
